- .eslintrc.js
- cdk/package.json
- package.json
- src/components/snet-blockchains-list/index.jsx
- src/components/snet-navigation/index.jsx
- src/layouts/GeneralLayout.jsx
- src/pages/Converter/HelpLinks.jsx
- src/services/redux/index.js
- src/services/redux/slices/blockchain/blockchainActions.js
- src/services/redux/slices/blockchain/blockchainSlice.js
- src/services/redux/utils.js
- src/utils/Axios.js
- src/utils/HttpRequests.js
1. Fetch available blockchains from the backend and render UI
> SNET-1226 Fetch available blockchains and render UI

- src/assets/theme/style.css
- src/components/snet-wallet-connector/walletHook.js
- src/index.js
`useWalletHook` has the following integrations
1. Connect with `metamask` & `walletconnect`
2. Sign message 
3. Disconnect wallet
> Web3Modal integration for managing wallets

- package.json
- src/components/snet-data-grid/Rows.jsx
- src/components/snet-data-grid/Transactions.jsx
- src/components/snet-data-grid/index.jsx
- src/pages/Converter/ADATOERC20ETH.jsx
- src/pages/Transactions/TxnHistoryTable.jsx
- src/pages/Transactions/hooks/conversionHistoryHook.js
- src/utils/HttpRequests.js
1. ETH-ADA Conversion display statuses only
2. Added refresh button txn history page
> Fixes: Txn history page

- src/components/snet-ada-eth-conversion-form/TransactionReceipt.jsx
- src/components/snet-conversion-status/index.jsx
- src/components/snet-data-grid/Rows.jsx
- src/pages/Converter/ADATOERC20ETH.jsx
1. DApp is not Initiate New Transaction and Continuing Old Transaction Stepped Window with New Value
2. View Transaction history redirects to Transactions
> SNET-1381 SNET-1396 Bug fixes

- src/components/snet-ada-eth-conversion-form/ClaimTokens.jsx
- src/components/snet-ada-eth-conversion-form/DepositAndBurnTokens.jsx
- src/components/snet-data-grid/Rows.jsx
- src/components/snet-data-grid/Transactions.jsx
- src/components/snet-data-grid/index.jsx
- src/components/snet-snackbar/index.jsx
- src/pages/Converter/ADATOERC20ETH.jsx
- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/HelpLinks.jsx
- src/pages/Converter/hooks/ERC20TokenHook.js
- src/pages/Transactions/hooks/conversionHistoryHook.js
Fixes:
1. Display Deposit & Receiving amount on txn history page
2. Autoclose snack bar after 6 seconds in case any exceptions
3. ADA-ETH conversion: Incase Cardano address is not selected disable the convert button
4. Variable typo fix
> SNET-1405 SNET-1400 Bug fixes on transaction history page

- cdk/lib/ConverterPipelineStack.ts
- src/components/snet-ada-eth-conversion-form/TransactionReceipt.jsx
Fix: 
- Instead of redirecting to the transactions page on clicking the "Finish" button after conversion, display the home page.
- On codebuild checkout specified git branch
> SNET-1451 After clicking "Finish" button display home page

- src/components/snet-data-grid/Rows.jsx
- src/components/snet-snackbar/index.jsx
- src/components/snet-wallet-connector/walletHook.js
- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Transactions/hooks/conversionHistoryHook.js
Fixes:
1. Display error toast with link 
2. Maximum visible rows updated to 20
> SNET-1436 Bug fixes

- src/components/snet-snackbar/index.jsx
- src/components/snet-wallet-connector/walletHook.js
Fixed breaking the screen due to a typo in variable
> SNET-1436 Fix typo which caused breaking screen to blank

- src/components/snet-conversion-input/InputWithAssetDropdown.jsx
- src/components/snet-snackbar/index.jsx
- src/pages/Converter/PendingTxnAlert.jsx
- src/pages/Converter/index.jsx
- src/utils/HttpRequests.js
1. Display pending txn as alert on the home screen
2. Focus input when the page renders
3. Fix Snackbar View button
> Display pending txn as alert on home screen

- src/components/snet-wallet-connector/walletHook.js
- src/pages/Converter/ERC20TOADA.jsx
Changes in [walletHook.js](https://github.com/singnet/snet-converter-dapp/compare/development...raamb:development#diff-7e0c41c4f49089ff3cbdd010e7610bacd0a3f7d8ff14bc4ce0e968e6273484f5) do not cover all classes of errors. Will continue to iterate over this.
> Improved contract error message handling

- src/components/snet-navigation/WalletMenu.jsx
- src/pages/Converter/ERC20TOADA.jsx
Fixes:
- Convert and Authorize is still disabled (Scenario: When a user loads the page and by default, it is Cardano so entering the amount, when I switch the conversion then buttons are disabled)
- When a user clicks on home page, Redirect to Homepage irrespective of conversion screen
> SNET-1470 Bug fix

- src/components/snet-data-grid/Transactions.jsx
- src/components/snet-wallet-connector/walletHook.js
- src/pages/Converter/ADATOERC20ETH.jsx
- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/hooks/ERC20TokenHook.js
- src/services/redux/slices/blockchain/blockchainSlice.js
- src/utils/ConverterConstants.js
Fixes:
1. Display meaningful messages while making a conversion
2. Check Allowance when changing wallets on Metamask
3. On txn history page convert from cogs and display amount.
> SNET-1478 SNET-1470 Display meaningful messages while making a conversion 

- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/hooks/ConverterHook.js
- src/utils/ConverterConstants.js
- src/utils/bignumber.js
Fixes
1. Throw an error in case user enters more than the allowed decimal places
2. Switch to ETH-ADA conversion
3. Clear state after making a conversion
> SNET-1461 SNET-1482 SNET-1483 Fixes on Conversion form

- cdk/lib/ConverterPipelineStack.ts
- src/assets/theme/style.css
- src/pages/Converter/ERC20TOADA.jsx
Fix:
- Display the conversion button if the approval spend limit call is a success
- Codebuild is picking wrong files sometimes, fixing it by pruning the S3 bucket before the deployment
> SNET-1475 Display the conversion button if the approval spend limit call is a success

- src/pages/Converter/ERC20TOADA.jsx
- src/utils/ConverterConstants.js
- Removed unused variables
- Display the popup after confirming txn for ETH-ADA which can be closed and as per invision design
> SNET-1487 Fix: Bridge Missing Screen during ETH to ADA conversion

- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/PendingTxnAlert.jsx
- src/pages/Transactions/index.jsx
Continuation of PR: https://github.com/singnet/snet-converter-dapp/pull/124
> Conflict fix from PR 124

- package.json
- src/pages/Contact/index.jsx
- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/ETHTOADAConversionPopup.jsx
- src/pages/Converter/hooks/ERC20TokenHook.js
- src/pages/Converter/index.jsx
- src/pages/Transactions/index.jsx
- src/utils/ConverterConstants.js
- Fix Block confirmation popup on ETH-ADA conversion
- Display Title on Home page, Contact us page, Txn History page
> SNET-1487 Fix: Block confirmation popup on ETH-ADA conversion

- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/hooks/ERC20TokenHook.js
1. Close block confirmation popup on close button click 
2. Stop invoking API calls after confirmation is success
> Fix : Blockconfirmation Popup

- src/components/snet-ada-eth-conversion-form/DepositAndBurnTokens.jsx
- src/pages/Converter/ADATOERC20ETH.jsx
- src/services/redux/slices/tokenPairs/tokenPairSlice.js
Display appropriate status and icon on the converter stepper based on the operations
> ADA-ETH Stepper enhancement

- src/components/snet-ada-eth-conversion-form/SnetAdaEthSteps.jsx
- src/pages/Converter/ADATOERC20ETH.jsx
- src/services/redux/slices/tokenPairs/tokenPairSlice.js
Fixes:
- Display appropriate icon based on the current status
- Reset ADA-ETH conversion steps if user is clicked cancel or continue later
> SNET-1597 Stepper icons for ADA-ETH & Reset conversion steps

- src/pages/Converter/index.jsx
Deposit tokens from Cardano wallet to the derived deposit address
> SNET-1606 Deposit tokens From Cardano wallet

- src/libraries/useInjectableWalletHook.js
- src/pages/Converter/index.jsx
Fix:
- Transfer tokens from the selected wallet by the user
> Update transfer tokens from Wallet selected

- src/components/snet-blockchains-list/index.jsx
- src/components/snet-connect-wallets/index.jsx
- src/utils/ConverterConstants.js
- dapp supports connecting to Cardano chain with multiple wallet options
- Removed capturing Cardano wallet address as input
> SNET-1640 Enabled Cardano chain with multiple wallet options

- src/components/snet-connect-wallets/index.jsx
- src/components/snet-conversion-info/ReadyToClaim.jsx
- src/components/snet-conversion-info/index.jsx
- src/components/snet-data-grid/Rows.jsx
- src/components/snet-data-grid/index.jsx
- src/libraries/useInjectableWalletHook.js
- src/pages/Converter/index.jsx
- src/utils/ConverterConstants.js
Remove the stepper flow and display conversion details on a modal.
> SNET-1642 ADA-ETH Remove the stepper flow

- src/components/snet-conversion-info/ReadyToClaim.jsx
- src/components/snet-conversion-info/index.jsx
- src/components/snet-data-grid/index.jsx
Fix:
- Close the modal popup when a user click the close icon
- Display the appropriate title
- Close the modal after wallet interaction
> SNET-1642 Fix: Close the popup and display the conversion title

- src/components/snet-conversion-info/ReadyToClaim.jsx
- src/components/snet-conversion-info/index.jsx
- src/components/snet-data-grid/Rows.jsx
- src/components/snet-data-grid/index.jsx
- src/pages/Converter/ETHTOADAConversionPopup.jsx
- src/pages/Converter/index.jsx
Manage awaiting confirmation screen flow for both ETH to ADA and ADA to ETH.
Display confirmation and claim popup from transaction screen.
> Display awaiting confirmation screen

- src/components/snet-conversion-info/ReadyToClaim.jsx
- src/components/snet-conversion-info/index.jsx
- src/libraries/useInjectableWalletHook.js
1. Close modal popup if anything goes wrong on metamask / wallet connect (cancel / close/other exceptions)
2. Fix error: Randomly seeing  Not enough ADA leftover to include non-ADA assets in a change
> Fixes: Stepper flow ADA-ETH

- src/components/snet-conversion-info/ReadyToClaim.jsx
- src/components/snet-conversion-status/index.jsx
- src/components/snet-conversion-status/styles.js
- src/pages/Converter/ERC20TOADA.jsx
- src/pages/Converter/hooks/ERC20TokenHook.js
- Change claim popup loader icon.
- Update awaiting confirmation for burning and mining process for ETH to ADA.
> Update ETH to ADA confirmation flow and claim popup UI

- package.json
- src/libraries/useInjectableWalletHook.js
1. Listen to account change
2. Listen Cardano network change
> SNET-1678 Listen to Cardano events

- src/components/snet-conversion-info/index.jsx
- src/services/redux/slices/wallet/walletSlice.js
Bugfix: Not showing claim tokens popup after block confirmation. Changed the boolean flag to redux state instead of consuming from react component.
> SNET-1683 Bugfix: Not showing claim tokens popup after block confirmation
